USE [master]
GO
/****** Object:  Database [JonielDb]    Script Date: 23/02/2024 00:35:53 ******/
CREATE DATABASE [JonielDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JonielDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\JonielDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JonielDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\JonielDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [JonielDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JonielDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JonielDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JonielDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JonielDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JonielDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JonielDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [JonielDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JonielDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JonielDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JonielDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JonielDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JonielDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JonielDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JonielDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JonielDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JonielDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [JonielDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JonielDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JonielDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JonielDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JonielDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JonielDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JonielDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JonielDb] SET RECOVERY FULL 
GO
ALTER DATABASE [JonielDb] SET  MULTI_USER 
GO
ALTER DATABASE [JonielDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JonielDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JonielDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JonielDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JonielDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JonielDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'JonielDb', N'ON'
GO
ALTER DATABASE [JonielDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [JonielDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [JonielDb]
GO
/****** Object:  Table [dbo].[Fornecedor]    Script Date: 23/02/2024 00:35:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Fornecedor](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CNPJ] [varchar](14) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Cidade] [varchar](50) NOT NULL,
	[Estado] [varchar](2) NOT NULL,
	[Bairro] [varchar](50) NOT NULL,
	[Rua] [varchar](100) NOT NULL,
	[Numero] [varchar](10) NOT NULL,
	[Complemento] [varchar](50) NULL,
	[Ativo] [bit] NOT NULL,
	[CreateDate] [varchar](22) NULL,
	[UpdateDate] [varchar](22) NULL,
	[CEP] [varchar](8) NOT NULL,
 CONSTRAINT [PK_FORNECEDOR_ID] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 23/02/2024 00:35:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Usuario] [varchar](100) NOT NULL,
	[Senha] [varchar](100) NOT NULL,
	[CreateDate] [varchar](22) NULL,
	[UpdateDate] [datetime] NULL,
 CONSTRAINT [PK_LOGIN_ID] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Produto]    Script Date: 23/02/2024 00:35:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Produto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FornecedorId] [int] NOT NULL,
	[Nome] [varchar](100) NOT NULL,
	[Quantidade] [int] NOT NULL,
	[CreateDate] [varchar](22) NULL,
	[UpdateDate] [varchar](22) NULL,
 CONSTRAINT [PK_PRODUTO_ID] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Produto]  WITH CHECK ADD  CONSTRAINT [FK_PRODUTO_FORNECEDOR_FORNECEDORID] FOREIGN KEY([FornecedorId])
REFERENCES [dbo].[Fornecedor] ([Id])
GO
ALTER TABLE [dbo].[Produto] CHECK CONSTRAINT [FK_PRODUTO_FORNECEDOR_FORNECEDORID]
GO
USE [master]
GO
ALTER DATABASE [JonielDb] SET  READ_WRITE 
GO
